### ISSUE TITLE
Bump dependencies + PR for Superstruct?

### ISSUE THREAD

**Issue by BuyMyBeard** [birchill/discriminator#2]
Hello!
I have found myself reliant on your library to help with validating object unions. At the moment, your peer dependendencies cause an unmet peer with Superstruct, since they updated to v2.0.0 in july­. Do you plan on maintaining this library? 

I also saw in some issues the Superstruct maintainers were open to receiving this feature into their repo. You said you had to clean it up first. How is that faring? Could I do it for you?

**Comment by birtles** [comment]
Hi @BuyMyBeard! Yes, I've been meaning to update the dependencies.

I'd also love to get this into superstruct proper but just haven't had the time to tidy it up. From memory the typings might not be quite right in some cases and there may also have been a case of having multiple discriminators that it couldn't realise.

If you have time to work on a PR for superstruct, please go for it!

I'll update the dependencies for this for now.
